# -*- coding: utf-8 -*-
"""programa3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H_ENLYvwL6pa5UQaMzL-3dlnxWZNa56T
"""

class Persona:

	def inicializar(self):

		self.nombre= input('Ingrese el nombre de la persona: ')
		self.edad= int(input('Ingrese la edad: '))

	def mostrar(self):
		print('Nombre:', self.nombre)
		print('Edad:', self.edad)


	def mayor_de_edad(self):
		if self.edad>=18:
			print('\nSi es mayor de edad (18 años)')

		else:
			print('\nNo es mayor edad')

#___________________________BLOQUE PRINCIPAL_________________________________________

# Objeto 1
persona1= Persona()
persona1.inicializar()
persona1.mostrar()
persona1.mayor_de_edad()

# Objeto 2
persona2 = Persona()
persona2.inicializar()
persona2.mostrar()
persona2.mayor_de_edad()