# -*- coding: utf-8 -*-
"""tarea

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H_ENLYvwL6pa5UQaMzL-3dlnxWZNa56T
"""

class Persona:

    def inicializar(self,nom):
        self.nombre=nom

    def imprimir(self):
        print("Nombre",self.nombre)


# bloque principal

persona1=Persona()
persona1.inicializar("Pedro")
persona1.imprimir()

persona2=Persona()
persona2.inicializar("Carla")
persona2.imprimir()